### ISSUE TITLE
Clarification regarding Task 2::Basic::Subtask 2

### ISSUE THREAD

**Issue by ankurdubey521** [acmbitmesra/DevHack-0.2#1]
1)Are we supposed to create a MD file with a table containing an entry only for our team or for all teams ?
2)If one team member can create an entry with the requested contest, is it necessary that the 2nd team member create a pull requested with the same data again?

**Comment by sarthakgupta072** [comment]
> 1)1)Are we supposed to create a MD file with a table containing an entry only for our team or for all teams?

You have to make changes in this file https://github.com/acmbitmesra/DevHack-0.2/blob/master/Leaderboard/After%20Task-1.md . Not in readme.md.

> 2)If one team member can create an entry with the requested contest, is it necessary that the 2nd team member create a pull requested with the same data again?

All members have to contribute in some form. May be add only your name in your pull request, not your team mate's name.

**Comment by sarthak-sopho** [comment]
ok. You changed the file name to After Task1.md. Good! Merged that.

**Comment by ankurdubey521** [comment]
Thanks ! Should I close the issue?
